"""
google_tools.py — BurnoutShield Google Integrations (Enhanced Web OAuth)

Provides deep integration with Google Workspace:
  - get_calendar_events()       → Today's Google Calendar events + Google Meet detection
  - get_gmail_signals()         → Urgent email signal detection from Gmail
  - analyze_calendar_pressure() → Back-to-back, meeting hours, overload detection
  - analyze_exhaustion()        → Combined exhaustion scoring from all Google signals

Authentication:
  - Exclusively uses `token.json` generated by the Flask Web OAuth flow.
  - If `token.json` is missing or invalid, it gracefully falls back to realistic mock data.
"""

import os
import logging
import datetime
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

CALENDAR_ENABLED = os.getenv("GOOGLE_CALENDAR_ENABLED", "false").lower() == "true"
GMAIL_ENABLED    = os.getenv("GOOGLE_GMAIL_ENABLED",    "false").lower() == "true"

# Path resolution: credentials live in the project root
_PROJECT_ROOT    = Path(__file__).parent.parent
TOKEN_FILE       = _PROJECT_ROOT / "token.json"

SCOPES = [
    "https://www.googleapis.com/auth/calendar.readonly",
    "https://www.googleapis.com/auth/gmail.readonly",
]


# ── Authentication ────────────────────────────────────────────────────────────

def _get_google_creds():
    """
    Returns valid Google credentials from the token.json generated by the app's Web Flow.
    Automatically refreshes the token if expired.
    Returns None if unauthenticated.
    """
    if not TOKEN_FILE.exists():
        logging.info("[Google Auth] token.json not found — UI must login via Web OAuth. Using mock data.")
        return None

    try:
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request

        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            # Save the refreshed token
            with open(TOKEN_FILE, "w") as tok:
                tok.write(creds.to_json())

        if creds and creds.valid:
            # Optionally check if calendar/gmail access is actually granted
            return creds
            
        logging.warning("[Google Auth] token.json is invalid or expired with no refresh token.")
        return None

    except Exception as e:
        logging.warning(f"[Google Auth] Could not load or refresh token: {e}")
        return None


# ── Google Calendar ───────────────────────────────────────────────────────────

def get_calendar_events(max_results: int = 25) -> list[dict]:
    """
    Fetches today's Google Calendar events.
    Returns a list of dicts with keys: title, start, end, duration_min, etc.
    """
    if not CALENDAR_ENABLED:
        return _mock_calendar_events()

    creds = _get_google_creds()
    if not creds:
        return _mock_calendar_events()

    try:
        from googleapiclient.discovery import build

        service = build("calendar", "v3", credentials=creds, cache_discovery=False)

        now   = datetime.datetime.utcnow()
        start = now.replace(hour=0, minute=0, second=0, microsecond=0).isoformat() + "Z"
        end   = now.replace(hour=23, minute=59, second=59).isoformat() + "Z"

        events_result = (
            service.events()
            .list(
                calendarId="primary",
                timeMin=start,
                timeMax=end,
                maxResults=max_results,
                singleEvents=True,
                orderBy="startTime",
            )
            .execute()
        )

        raw_events = events_result.get("items", [])
        parsed = []

        for evt in raw_events:
            s = evt.get("start", {})
            e = evt.get("end", {})
            start_str = s.get("dateTime", s.get("date", ""))
            end_str   = e.get("dateTime", e.get("date", ""))
            is_all_day = "date" in s and "dateTime" not in s

            duration_min = 0
            if start_str and end_str and not is_all_day:
                try:
                    s_dt = datetime.datetime.fromisoformat(start_str.replace("Z", "+00:00"))
                    e_dt = datetime.datetime.fromisoformat(end_str.replace("Z", "+00:00"))
                    duration_min = int((e_dt - s_dt).total_seconds() / 60)
                except Exception:
                    pass

            # ── Google Meet / video conference detection ──
            meeting_link = ""
            has_google_meet = False
            location = evt.get("location", "")

            conf_data = evt.get("conferenceData", {})
            entry_points = conf_data.get("entryPoints", [])
            for ep in entry_points:
                if ep.get("entryPointType") == "video":
                    meeting_link = ep.get("uri", "")
                    break

            if not meeting_link and "hangoutLink" in evt:
                meeting_link = evt["hangoutLink"]
                has_google_meet = True
            elif meeting_link and "meet.google.com" in meeting_link:
                has_google_meet = True

            if not meeting_link and location.startswith("http"):
                meeting_link = location

            attendees = evt.get("attendees", [])

            parsed.append({
                "title":           evt.get("summary", "Untitled event"),
                "start":           start_str,
                "end":             end_str,
                "duration_min":    duration_min,
                "is_all_day":      is_all_day,
                "location":        location,
                "meeting_link":    meeting_link,
                "has_google_meet": has_google_meet,
                "attendee_count":  len(attendees),
                "is_recurring":    "recurringEventId" in evt,
                "status":          evt.get("status", "confirmed"),
                "organizer":       evt.get("organizer", {}).get("email", ""),
            })

        logging.info(f"[Calendar] Fetched {len(parsed)} event(s)")
        return parsed

    except Exception as e:
        logging.warning(f"[Calendar] API error: {e}")
        return _mock_calendar_events()


def analyze_calendar_pressure(events: list[dict]) -> dict:
    if not events:
        return {
            "total_meetings": 0, "total_meeting_hours": 0.0,
            "google_meet_count": 0, "back_to_back_count": 0,
            "longest_meeting_min": 0, "free_blocks": [],
            "meeting_density": 0.0, "early_meeting": False,
            "late_meeting": False, "pressure_level": "LOW",
        }

    timed = [e for e in events if not e.get("is_all_day", False) and e.get("duration_min", 0) > 0]
    total_meetings = len(timed)
    total_min = sum(e.get("duration_min", 0) for e in timed)
    total_hours = round(total_min / 60, 1)
    google_meet_count = sum(1 for e in timed if e.get("has_google_meet", False))
    longest = max((e.get("duration_min", 0) for e in timed), default=0)

    back_to_back = 0
    sorted_events = sorted(timed, key=lambda x: x.get("start", ""))
    for i in range(1, len(sorted_events)):
        try:
            prev_end = sorted_events[i - 1].get("end", "")
            curr_start = sorted_events[i].get("start", "")
            if prev_end and curr_start:
                pe = datetime.datetime.fromisoformat(prev_end.replace("Z", "+00:00"))
                cs = datetime.datetime.fromisoformat(curr_start.replace("Z", "+00:00"))
                gap_min = (cs - pe).total_seconds() / 60
                if gap_min < 15:
                    back_to_back += 1
        except Exception:
            pass

    early_meeting = False
    late_meeting = False
    for e in timed:
        try:
            start_str = e.get("start", "")
            end_str = e.get("end", "")
            if start_str:
                st = datetime.datetime.fromisoformat(start_str.replace("Z", "+00:00"))
                if st.hour < 9:
                    early_meeting = True
            if end_str:
                et = datetime.datetime.fromisoformat(end_str.replace("Z", "+00:00"))
                if et.hour >= 18:
                    late_meeting = True
        except Exception:
            pass

    workday_min = 9 * 60
    density = round((total_min / workday_min) * 100, 1) if workday_min > 0 else 0
    pressure_score = (total_meetings * 2 + back_to_back * 3 + (1 if early_meeting else 0) + (1 if late_meeting else 0) + google_meet_count * 1)

    if density > 70 or pressure_score >= 20: pressure_level = "CRITICAL"
    elif density > 50 or pressure_score >= 14: pressure_level = "HIGH"
    elif density > 30 or pressure_score >= 8: pressure_level = "MEDIUM"
    else: pressure_level = "LOW"

    return {
        "total_meetings": total_meetings, "total_meeting_hours": total_hours,
        "google_meet_count": google_meet_count, "back_to_back_count": back_to_back,
        "longest_meeting_min": longest, "free_blocks": [],
        "meeting_density": density, "early_meeting": early_meeting,
        "late_meeting": late_meeting, "pressure_level": pressure_level,
    }


def _mock_calendar_events() -> list[dict]:
    return [
        {"title": "Sprint planning", "start": "10:00", "end": "11:30", "duration_min": 90, "is_all_day": False, "location": "", "meeting_link": "https://meet.google.com/xyz", "has_google_meet": True, "attendee_count": 12, "is_recurring": True, "status": "confirmed"}
    ]


# ── Gmail Signals ─────────────────────────────────────────────────────────────

_URGENCY_KEYWORDS = [
    "urgent", "asap", "immediately", "deadline", "overdue",
    "action required", "follow up", "reminder", "time-sensitive",
    "critical", "escalation", "blocked", "blocker", "eod", "end of day",
]

_MEETING_KEYWORDS = [
    "meeting", "invite", "calendar", "reschedule", "agenda",
    "standup", "sync", "review", "demo", "presentation",
]


def get_gmail_signals(max_results: int = 30) -> list[dict]:
    if not GMAIL_ENABLED:
        return _mock_gmail_signals()

    creds = _get_google_creds()
    if not creds:
        return _mock_gmail_signals()

    try:
        from googleapiclient.discovery import build

        service = build("gmail", "v1", credentials=creds, cache_discovery=False)

        query = "is:unread newer_than:1d"
        results = (
            service.users()
            .messages()
            .list(userId="me", q=query, maxResults=max_results)
            .execute()
        )

        messages = results.get("messages", [])
        signals  = []

        for msg in messages:
            msg_data = (
                service.users()
                .messages()
                .get(userId="me", id=msg["id"], format="metadata",
                     metadataHeaders=["Subject", "From", "Date"])
                .execute()
            )

            headers = {h["name"]: h["value"] for h in msg_data.get("payload", {}).get("headers", [])}
            subject = headers.get("Subject", "")
            snippet = msg_data.get("snippet", "")
            sender  = headers.get("From", "")
            date    = headers.get("Date", "")

            combined_text = (subject + " " + snippet).lower()

            found_urgency = [kw for kw in _URGENCY_KEYWORDS if kw in combined_text]
            urgency_score = len(found_urgency) * 2

            found_meeting = [kw for kw in _MEETING_KEYWORDS if kw in combined_text]
            is_meeting_related = len(found_meeting) > 0

            if found_urgency or is_meeting_related:
                signals.append({
                    "subject": subject,
                    "snippet": snippet[:150],
                    "from": sender,
                    "date": date,
                    "urgency_keywords_found": found_urgency,
                    "urgency_score": urgency_score,
                    "is_meeting_related": is_meeting_related,
                })

        logging.info(f"[Gmail] {len(signals)} signal(s)")
        return signals

    except Exception as e:
        logging.warning(f"[Gmail] API error: {e}")
        return _mock_gmail_signals()


def analyze_email_pressure(signals: list[dict]) -> dict:
    if not signals:
        return {
            "total_urgent_emails": 0, "total_meeting_emails": 0,
            "max_urgency_score": 0, "top_urgent_subjects": [],
            "email_pressure_level": "LOW",
        }

    urgent = [s for s in signals if s.get("urgency_score", 0) > 0]
    meeting_related = [s for s in signals if s.get("is_meeting_related", False)]

    sorted_by_urgency = sorted(urgent, key=lambda x: x.get("urgency_score", 0), reverse=True)
    top_subjects = [s["subject"] for s in sorted_by_urgency[:3]]
    max_score = sorted_by_urgency[0].get("urgency_score", 0) if sorted_by_urgency else 0

    total_urgent = len(urgent)
    if total_urgent >= 8 or max_score >= 8: pressure = "CRITICAL"
    elif total_urgent >= 5 or max_score >= 6: pressure = "HIGH"
    elif total_urgent >= 3 or max_score >= 4: pressure = "MEDIUM"
    else: pressure = "LOW"

    return {
        "total_urgent_emails": total_urgent, "total_meeting_emails": len(meeting_related),
        "max_urgency_score": max_score, "top_urgent_subjects": top_subjects,
        "email_pressure_level": pressure,
    }


def _mock_gmail_signals() -> list[dict]:
    return [
        {
            "subject": "Action required: PR review blocking release",
            "snippet": "The PR is blocking the release pipeline. Can you review ASAP? This is critical for the sprint.",
            "from": "teammate@company.com",
            "date": "Today",
            "urgency_keywords_found": ["action required", "asap", "blocker", "critical"],
            "urgency_score": 8,
            "is_meeting_related": False,
        }
    ]


# ── Combined Exhaustion Analysis ──────────────────────────────────────────────

def analyze_exhaustion(
    calendar_events: list[dict], gmail_signals: list[dict],
    tasks: list[dict], meetings: list[dict], deadlines: list[dict]
) -> dict:
    cal_pressure = analyze_calendar_pressure(calendar_events)
    email_pressure = analyze_email_pressure(gmail_signals)

    score = 0
    stressors = []

    meeting_hours = cal_pressure.get("total_meeting_hours", 0)
    if meeting_hours >= 6: score += 30; stressors.append(f"Extreme meeting load: {meeting_hours}h")
    elif meeting_hours >= 4: score += 20; stressors.append(f"Heavy meeting load: {meeting_hours}h")
    elif meeting_hours >= 2: score += 10

    b2b = cal_pressure.get("back_to_back_count", 0)
    if b2b >= 3: score += 15; stressors.append(f"{b2b} back-to-back meetings without breaks")
    elif b2b >= 1: score += 8; stressors.append(f"{b2b} back-to-back meeting(s)")

    meet_count = cal_pressure.get("google_meet_count", 0)
    if meet_count >= 4: score += 10; stressors.append(f"{meet_count} video calls (fatigue risk)")

    urgent_emails = email_pressure.get("total_urgent_emails", 0)
    if urgent_emails >= 5: score += 15; stressors.append(f"{urgent_emails} urgent emails")
    elif urgent_emails >= 3: score += 10

    task_count = len(tasks)
    if task_count >= 12: score += 15; stressors.append("Too many tasks scheduled")
    
    critical_deadlines = [d for d in deadlines if d.get("severity") == "critical" or d.get("due") == "today"]
    if len(critical_deadlines) >= 2: score += 10; stressors.append("Multiple critical deadlines today")

    score = min(score, 100)
    if score >= 70: level = "SEVERE"
    elif score >= 45: level = "HIGH"
    elif score >= 25: level = "MODERATE"
    else: level = "LOW"

    return {
        "exhaustion_score": score,
        "exhaustion_level": level,
        "calendar_pressure": cal_pressure,
        "email_pressure": email_pressure,
        "key_stressors": stressors,
        "recommendations": [],
        "signal_summary": {
            "calendar_events": len(calendar_events),
            "urgent_emails": urgent_emails,
            "tasks": task_count,
        }
    }
